language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master
    - recette

env:
  global:
    secure: $GH_TOKEN

script:
  - npm install -g @angular/cli
  - ng build --prod
  - npm test
  - cp ./Dockerfile dist/AppliToDoDevOps
  - cd dist/AppliToDoDevOps
  - git init
  - git add --all
  - git commit "CommitFromTravis"
  - git remote add origin https://$GH_TOKEN@github.com/mimir02/AppliNodeDevOps.git
  - git push --force -u origin master

notifications:
  email:
    on_failure: change
    on_success: change