language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master
    - recette

env:
  global:
    secure: $GH_TOKEN

script:
  - ng build
  - npm test
  - git checkout recette
  - git rm .travis.yml
  - git commit -m "Commit from travis from recette branch"
  - git push --force https://$GH_TOKEN@github.com/mimir02/AppliNodeDevOps.git dev:docker-recette

notifications:
  email:
    on_failure: change
    on_success: change