language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master
    - recette

env:
  global:
    secure: $GH_TOKEN

script:
  - ng build
  - npm test

after-script:
  - npm install -g @angular/cli
  - ng build
  - ls

notifications:
  email:
    on_failure: change
    on_success: change